### ISSUE TITLE
Issue for unexecutable file

### ISSUE THREAD

**Issue by laylanime** [TheRLMacaron/EPYTHRION-Early-Access#1]
Please update your release of your game by uploading zip file which contains all files like the three files because its make easier..

Don;t understands then come to our place we can show you guys

Humbly,
Froms The Zombie Squad

**Comment by TheRLMacaron** [comment]
look up

**Comment by TheRLMacaron** [comment]
really helpful did not realize it was a pain in the ahh to downlaod them

**Comment by TheRLMacaron** [comment]
thanks a bunch 👍👍😄
